// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Fitness_cpp
double Fitness_cpp(arma::vec x, arma::vec Y, arma::mat X, arma::vec Z, arma::vec pi, double tolerance);
RcppExport SEXP _LorenzRegression_Fitness_cpp(SEXP xSEXP, SEXP YSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP piSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(Fitness_cpp(x, Y, X, Z, pi, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// Fitness_meanrank
double Fitness_meanrank(arma::vec x, arma::vec Y, arma::mat X, arma::vec pi, double tolerance);
RcppExport SEXP _LorenzRegression_Fitness_meanrank(SEXP xSEXP, SEXP YSEXP, SEXP XSEXP, SEXP piSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(Fitness_meanrank(x, Y, X, pi, tolerance));
    return rcpp_result_gen;
END_RCPP
}
// PLR_derivative_cpp_m
arma::vec PLR_derivative_cpp_m(arma::vec derz, arma::vec y, arma::vec ycum, int y_skipped, arma::mat X, arma::vec pi, arma::vec theta, double h, double gamma, int kernel);
RcppExport SEXP _LorenzRegression_PLR_derivative_cpp_m(SEXP derzSEXP, SEXP ySEXP, SEXP ycumSEXP, SEXP y_skippedSEXP, SEXP XSEXP, SEXP piSEXP, SEXP thetaSEXP, SEXP hSEXP, SEXP gammaSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type derz(derzSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ycum(ycumSEXP);
    Rcpp::traits::input_parameter< int >::type y_skipped(y_skippedSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(PLR_derivative_cpp_m(derz, y, ycum, y_skipped, X, pi, theta, h, gamma, kernel));
    return rcpp_result_gen;
END_RCPP
}
// PLR_derivative_cpp_zero
arma::vec PLR_derivative_cpp_zero(arma::vec y, arma::vec ycum, arma::mat X, arma::vec pi, arma::vec theta, double h, double gamma, int kernel);
RcppExport SEXP _LorenzRegression_PLR_derivative_cpp_zero(SEXP ySEXP, SEXP ycumSEXP, SEXP XSEXP, SEXP piSEXP, SEXP thetaSEXP, SEXP hSEXP, SEXP gammaSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ycum(ycumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(PLR_derivative_cpp_zero(y, ycum, X, pi, theta, h, gamma, kernel));
    return rcpp_result_gen;
END_RCPP
}
// PLR_loss_cpp_m
double PLR_loss_cpp_m(double lossz, arma::mat X, arma::vec y, arma::vec ycum, int y_skipped, arma::vec pi, arma::vec theta, double h, double gamma, int kernel);
RcppExport SEXP _LorenzRegression_PLR_loss_cpp_m(SEXP losszSEXP, SEXP XSEXP, SEXP ySEXP, SEXP ycumSEXP, SEXP y_skippedSEXP, SEXP piSEXP, SEXP thetaSEXP, SEXP hSEXP, SEXP gammaSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lossz(losszSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ycum(ycumSEXP);
    Rcpp::traits::input_parameter< int >::type y_skipped(y_skippedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(PLR_loss_cpp_m(lossz, X, y, ycum, y_skipped, pi, theta, h, gamma, kernel));
    return rcpp_result_gen;
END_RCPP
}
// PLR_loss_cpp_zero
double PLR_loss_cpp_zero(arma::mat X, arma::vec y, arma::vec ycum, arma::vec pi, double h, double gamma, int kernel);
RcppExport SEXP _LorenzRegression_PLR_loss_cpp_zero(SEXP XSEXP, SEXP ySEXP, SEXP ycumSEXP, SEXP piSEXP, SEXP hSEXP, SEXP gammaSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type ycum(ycumSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(PLR_loss_cpp_zero(X, y, ycum, pi, h, gamma, kernel));
    return rcpp_result_gen;
END_RCPP
}
// SCAD_derivative_cpp
arma::vec SCAD_derivative_cpp(arma::vec x, double lambda, double a);
RcppExport SEXP _LorenzRegression_SCAD_derivative_cpp(SEXP xSEXP, SEXP lambdaSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(SCAD_derivative_cpp(x, lambda, a));
    return rcpp_result_gen;
END_RCPP
}
// frac_rank_cpp
arma::vec frac_rank_cpp(arma::vec x, arma::vec pi);
RcppExport SEXP _LorenzRegression_frac_rank_cpp(SEXP xSEXP, SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    rcpp_result_gen = Rcpp::wrap(frac_rank_cpp(x, pi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LorenzRegression_Fitness_cpp", (DL_FUNC) &_LorenzRegression_Fitness_cpp, 6},
    {"_LorenzRegression_Fitness_meanrank", (DL_FUNC) &_LorenzRegression_Fitness_meanrank, 5},
    {"_LorenzRegression_PLR_derivative_cpp_m", (DL_FUNC) &_LorenzRegression_PLR_derivative_cpp_m, 10},
    {"_LorenzRegression_PLR_derivative_cpp_zero", (DL_FUNC) &_LorenzRegression_PLR_derivative_cpp_zero, 8},
    {"_LorenzRegression_PLR_loss_cpp_m", (DL_FUNC) &_LorenzRegression_PLR_loss_cpp_m, 10},
    {"_LorenzRegression_PLR_loss_cpp_zero", (DL_FUNC) &_LorenzRegression_PLR_loss_cpp_zero, 7},
    {"_LorenzRegression_SCAD_derivative_cpp", (DL_FUNC) &_LorenzRegression_SCAD_derivative_cpp, 3},
    {"_LorenzRegression_frac_rank_cpp", (DL_FUNC) &_LorenzRegression_frac_rank_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_LorenzRegression(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
